# step-pretty-workplace-notify: Docker Compose
# https://docs.docker.com/compose/
#
# Usage: test up
version: '3'
services:

  # app test
  app:
    build:
      context: .
      dockerfile: docker/app-test/Dockerfile
